version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kelby-portfolio
    ports:
      - "8509:8509"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
    volumes:
      - .:/app
    restart: unless-stopped
    # For Windows Docker Desktop, ensure proper file permission handling
    # by mounting as read-only where appropriate
    # For production, remove the volume mount above